/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author alisson_formento
 */
public class Interface02 extends javax.swing.JFrame {

    /**
     * Creates new form Interface02
     */
    public Interface02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoSuperior = new javax.swing.JLabel();
        botao = new javax.swing.JButton();
        campoInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        textoSuperior.setBackground(new java.awt.Color(0, 153, 153));
        textoSuperior.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textoSuperior.setForeground(new java.awt.Color(0, 255, 153));
        textoSuperior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoSuperior.setText("TEXTO INICIAL");
        textoSuperior.setToolTipText("");

        botao.setBackground(new java.awt.Color(204, 204, 204));
        botao.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        botao.setForeground(new java.awt.Color(0, 0, 0));
        botao.setText("CLIQUE AQUI");
        botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoActionPerformed(evt);
            }
        });

        campoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botao, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addComponent(campoInput))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(textoSuperior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(66, 66, 66)
                .addComponent(campoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoActionPerformed
        String texto = campoInput.getText();
        textoSuperior.setText(texto);
    }//GEN-LAST:event_botaoActionPerformed

    private void campoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoInputActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao;
    private javax.swing.JTextField campoInput;
    private javax.swing.JLabel textoSuperior;
    // End of variables declaration//GEN-END:variables
}
